USE [master]
GO

/****** Object:  Database [universe]    Script Date: 2/6/2024 5:25:01 AM ******/
CREATE DATABASE [universe]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'universe', FILENAME = N'D:\Sql\MSSQL16.MSSQLSERVER\MSSQL\DATA\universe.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'universe_log', FILENAME = N'D:\Sql\MSSQL16.MSSQLSERVER\MSSQL\DATA\universe_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [universe].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [universe] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [universe] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [universe] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [universe] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [universe] SET ARITHABORT OFF 
GO

ALTER DATABASE [universe] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [universe] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [universe] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [universe] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [universe] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [universe] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [universe] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [universe] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [universe] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [universe] SET  ENABLE_BROKER 
GO

ALTER DATABASE [universe] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [universe] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [universe] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [universe] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [universe] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [universe] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [universe] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [universe] SET RECOVERY FULL 
GO

ALTER DATABASE [universe] SET  MULTI_USER 
GO

ALTER DATABASE [universe] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [universe] SET DB_CHAINING OFF 
GO

ALTER DATABASE [universe] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [universe] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [universe] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [universe] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [universe] SET QUERY_STORE = ON
GO

ALTER DATABASE [universe] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [universe] SET  READ_WRITE 
GO

